#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    bld(
            features='c cprogram',
            vapi_dirs='../../vapi',
            includes='. src vapi',
            packages='libgpod-1.0',
            target='../../syncPodList',
            uselib='GPOD',
            source=bld.path.ant_glob(incl='*.vala')            
            )


