AR = '/usr/bin/ar'
ARFLAGS = 'rcs'
BINDIR = '/usr/local/bin'
CC = ['/usr/bin/gcc']
CCDEFINES_ST = '-D%s'
CCFLAGS_DEBUG = ['-g']
CCFLAGS_GTHREAD = ['-pthread']
CCFLAGS_GTK+ = ['-pthread']
CCFLAGS_MACBUNDLE = ['-fPIC']
CCFLAGS_RELEASE = ['-O2']
CCLNK_SRC_F = ''
CCLNK_TGT_F = ['-o', '']
CC_NAME = 'gcc'
CC_SRC_F = ''
CC_TGT_F = ['-c', '-o', '']
CC_VERSION = ('4', '7', '2')
COMPILER_CC = 'gcc'
CPP = '/usr/bin/cpp'
CPPPATH_GLIB = ['/usr/include/glib-2.0', '/usr/lib/glib-2.0/include']
CPPPATH_GOBJECT = ['/usr/include/glib-2.0', '/usr/lib/glib-2.0/include']
CPPPATH_GTHREAD = ['/usr/include/glib-2.0', '/usr/lib/glib-2.0/include']
CPPPATH_GTK+ = ['/usr/include/gtk-2.0', '/usr/lib/gtk-2.0/include', '/usr/include/pango-1.0', '/usr/include/atk-1.0', '/usr/include/cairo', '/usr/include/pixman-1', '/usr/include/libdrm', '/usr/include/libpng15', '/usr/include/gdk-pixbuf-2.0', '/usr/include/harfbuzz', '/usr/include/glib-2.0', '/usr/lib/glib-2.0/include', '/usr/include/freetype2']
CPPPATH_ST = '-I%s'
CXXFLAGS_GTHREAD = ['-pthread']
CXXFLAGS_GTK+ = ['-pthread']
DATADIR = '/usr/local/share'
DATAROOTDIR = '/usr/local/share'
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
DOCDIR = '/usr/local/share/doc/waf-vala-template'
DVIDIR = '/usr/local/share/doc/waf-vala-template'
EXEC_PREFIX = '/usr/local'
FULLSTATIC_MARKER = '-static'
HAVE_GLIB = 1
HAVE_GOBJECT = 1
HAVE_GTHREAD = 1
HAVE_GTK_ = 1
HTMLDIR = '/usr/local/share/doc/waf-vala-template'
INCLUDEDIR = '/usr/local/include'
INFODIR = '/usr/local/share/info'
LIBDIR = '/usr/local/lib'
LIBEXECDIR = '/usr/local/libexec'
LIBPATH_ST = '-L%s'
LIB_GLIB = ['glib-2.0']
LIB_GOBJECT = ['gobject-2.0', 'glib-2.0']
LIB_GTHREAD = ['gthread-2.0', 'rt', 'glib-2.0']
LIB_GTK+ = ['gtk-x11-2.0', 'gdk-x11-2.0', 'pangocairo-1.0', 'atk-1.0', 'cairo', 'gdk_pixbuf-2.0', 'gio-2.0', 'pangoft2-1.0', 'pango-1.0', 'gobject-2.0', 'glib-2.0', 'freetype', 'fontconfig']
LIB_ST = '-l%s'
LINKFLAGS_GTHREAD = ['-pthread']
LINKFLAGS_GTK+ = ['-pthread']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINK_CC = ['/usr/bin/gcc']
LOCALEDIR = '/usr/local/share/locale'
LOCALSTATEDIR = '/usr/local/var'
MANDIR = '/usr/local/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = 'waf-vala-template'
PACKAGE_NAME = 'waf-vala-template'
PACKAGE_STRING = 'waf-vala-template-0.0.4'
PACKAGE_VERSION = 'waf-vala-template-0.0.4'
PDFDIR = '/usr/local/share/doc/waf-vala-template'
PREFIX = '/usr/local'
PSDIR = '/usr/local/share/doc/waf-vala-template'
RANLIB = '/usr/bin/ranlib'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/usr/local/sbin'
SHAREDSTATEDIR = '/usr/local/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STATICLIBPATH_ST = '-L%s'
STATICLIB_MARKER = '-Wl,-Bstatic'
STATICLIB_ST = '-l%s'
SYSCONFDIR = '/usr/local/etc'
VALAC = '/usr/bin/valac'
VALAC_VERSION = (0, 19, 0)
VALAFLAGS = ''
VERSION = '0.0.4'
VERSION_MAJOR_MINOR = '0.0'
defines = {'PACKAGE': '"waf-vala-template"', 'PACKAGE_VERSION': '"waf-vala-template-0.0.4"', 'HAVE_GTK_': 1, 'HAVE_GTHREAD': 1, 'HAVE_GOBJECT': 1, 'VERSION': '"0.0.4"', 'PACKAGE_STRING': '"waf-vala-template-0.0.4"', 'PACKAGE_NAME': '"waf-vala-template"', 'VERSION_MAJOR_MINOR': '"0.0"', 'HAVE_GLIB': 1}
macbundle_PATTERN = '%s.bundle'
program_PATTERN = '%s'
shlib_CCFLAGS = ['-fPIC', '-DPIC']
shlib_LINKFLAGS = ['-shared']
shlib_PATTERN = 'lib%s.so'
staticlib_LINKFLAGS = ['-Wl,-Bstatic']
staticlib_PATTERN = 'lib%s.a'
