#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008
# Thomas Nagy, 2010

def build(bld):
    print('sub-build ...')
    bld(
            features      = 'c cprogram',
            #vapi_dirs     = '../vapi',
            includes      = '.',
            packages      = 'libtaginfo_c gio-2.0 sqlheavy-0.1',
            target        = 'collection',
            uselib        = 'TAGINFO GIO SQLHEAVY',
            source = bld.path.ant_glob(incl = '*.vala')            
            )

